aquasecurity/trivy-db

- pkg/vulnsrc/bundler/bundler.go
- pkg/vulnsrc/cargo/cargo.go
- pkg/vulnsrc/composer/composer.go
- pkg/vulnsrc/node/node.go
- pkg/vulnsrc/python/python.go
- pkg/vulnsrc/vulnsrc.go
The severities of os packages from each vendor are already inserted into DB, but I forgot to insert the severities of library vulnerabilities to DB.
> fix(severity): insert severities of library vulnerabilities

- pkg/github/github.go
- pkg/github/github_test.go
Currently, trivy-db checks `published_at` and removes old releases. If a job continues to fail, the jobs would be old. In that case, all releases are removed. We would like to keep at least 3 releases.
> fix(github): skip removing releases when there are few release

- go.mod
- go.sum
- pkg/utils/utils.go
- pkg/utils/utils_test.go
- pkg/vulnsrc/oracle-oval/oracle-oval.go
- pkg/vulnsrc/oracle-oval/oracle-oval_test.go
- pkg/vulnsrc/oracle-oval/testdata/vuln-list/oval/oracle/2007/ELSA-2007-0057.json
- pkg/vulnsrc/oracle-oval/types.go
- pkg/vulnsrc/vulnerability/const.go
- pkg/vulnsrc/vulnerability/vulnerability.go
- pkg/vulnsrc/vulnsrc.go
Support Oracle Linux Security Advisory.
related: https://github.com/aquasecurity/vuln-list-update/pull/18
```
{
"Title": "\nELSA-2007-0123:  Moderate: cups security update  (MODERATE)\n",
"Description": "\n [1.1.22-0.rc1.9.18]\n - REVERTED these changes:\n   - Applied patch from STR #1301 (bug #195354).\n   - Patch pdftops to understand 'includeifexists', and use that in the\n     pdftops.conf file (bug #188583).\n   - Clear the printer's state_message and state_reasons after successful\n     job completion (bug #187457).\n   - Include dest-cache-v2 patch (bug #175847).\n   - Back-ported CUPS 1.2.x change to fix out of order IPP jobs (bug #171142).\n   - Back-ported large file support (bug #211915).\n   - Back-ported HTTP timing fix for STR #1020 (bug #194025).\n \n [1.1.22-0.rc1.9.16]\n …
```
> feat(oracle) Add oracle linux oval

- .github/workflows/cron.yml
- Dockerfile
- Makefile
- README.md
This adds a Dockerfile so the trivy-db.gzip can be built locally.
I've made some changes to the github workflow
* use tar.gz instead of the .zip archive for vuln-list (zip is 350MB vs. 121MB as .tar.gz)
* use wget instead of git to get the master tarballs
That should make it faster and I can send a PR for the gh workflow if desired.
Eventually the next step would be to provide a solution to https://github.com/aquasecurity/trivy/issues/294 so trivy can use the container including the trivy.db.gz
> Add Dockerfile to build trivy-db locally

- pkg/db/db.go
- pkg/db/db_test.go
- pkg/vulnsrc/vulnsrc.go
- pkg/vulnsrc/vulnsrc_test.go
Currently if the fields are not set, we will return empty JSON, which isn't so appealing to look at through something like `trivy -version` output.
This PR also  adds tests as there  were none.
Part of: https://github.com/aquasecurity/harbor-scanner-trivy/issues/48
> db: Add JSON tags and tests for it

- pkg/vulnsrc/nvd/nvd_test.go
Currently golangci-lint fails https://github.com/aquasecurity/trivy-db/runs/672505572
This is a misleading error as it can be seen here: https://github.com/golangci/golangci-lint/issues/825
> mod: Fix bbolt import name issue

- pkg/types/types.go
- pkg/vulnsrc/nvd/types.go
- pkg/vulnsrc/vulnerability/vulnerability.go
- pkg/vulnsrc/vulnerability/vulnerability_test.go
- pkg/vulnsrc/vulnsrc.go
- pkg/vulnsrc/vulnsrc_test.go
Addresses: https://github.com/aquasecurity/trivy/issues/92
> vulnsrc: Add CVSS scores to output in addition to vectors

- pkg/vulnsrc/alpine/alpine.go
- pkg/vulnsrc/amazon/amazon.go
- pkg/vulnsrc/amazon/amazon_test.go
- pkg/vulnsrc/debian-oval/debian-oval.go
- pkg/vulnsrc/debian/debian.go
- pkg/vulnsrc/redhat-oval/redhat-oval.go
- pkg/vulnsrc/ubuntu/ubuntu.go
Noticed that some error values referenced wrong VulnSrc names 🧐 
Also tried to make some of the VulnSrc name capitalization more consistent within their files (e.g `amazon` vs `Amazon`)
> fix(vulnsrc): fix error values referencing wrong vuln src

- .gitignore
- pkg/types/types.go
- pkg/vulnsrc/nvd/nvd.go
- pkg/vulnsrc/nvd/nvd_test.go
- pkg/vulnsrc/nvd/testdata/vuln-list/nvd/CVE-2020-0001.json
- pkg/vulnsrc/nvd/types.go
- pkg/vulnsrc/vulnerability/vulnerability.go
- pkg/vulnsrc/vulnerability/vulnerability_test.go
- pkg/vulnsrc/vulnsrc.go
- pkg/vulnsrc/vulnsrc_test.go
NVD has information regarding CWE-ID such as CWE-89 (SQL Injection). This information is useful to filter vulnerabilities in trivy. For example, we might be able to ignore CWE-20 (Improper Input Validation) depending on the service.
https://nvd.nist.gov/vuln/detail/CVE-2020-11010
> feat(nvd): add CWE-ID

- pkg/vulnsrc/nvd/nvd.go
- pkg/vulnsrc/nvd/nvd_test.go
[Issue](https://github.com/aquasecurity/trivy-db/issues/53)
NVD also have Reject vulnerabilities
(https://github.com/aquasecurity/vuln-list/blob/623ee07c1fb459caec78e297db201844a2a4e296/nvd/2016/CVE-2016-7345.json#L18)
> Ignore rejected vulnerabilities

- pkg/vulnsrc/cargo/cargo.go
- pkg/vulnsrc/cargo/cargo_test.go
- pkg/vulnsrc/cargo/testdata/crates/bitvec/RUSTSEC-2020-0007.toml
[Issue](https://github.com/aquasecurity/trivy-db/issues/66)
> Fix: Support v2 format in cargo

- go.mod
- pkg/types/types.go
- pkg/utils/time.go
- pkg/vulnsrc/nvd/nvd.go
- pkg/vulnsrc/nvd/nvd_test.go
- pkg/vulnsrc/vulnerability/vulnerability_test.go
When NVD doesn't have information, it displays "0001-01-01T00:00:00" now, but I think we should omit it.
> fix(vulnerability): use pointer of time.Time

- pkg/vulnsrc/ghsa/ghsa.go
- pkg/vulnsrc/ghsa/ghsa_test.go
GHSA recently added an empty CVE-ID as follows.
```
{
"Type": "CVE",
"Value": ""
}
```
https://github.com/aquasecurity/vuln-list/commit/1972b6aa3742ccf03b69c4cc1ea98756e3df5fe9#diff-6cf63dea72daa86aeb93472481cace60e174754ca91d55a2005092d1fe169518
Inserting into the DB has been failing because this was an unexpected value.
> fix(ghsa): handle empty CVE-ID

- pkg/db/advisory_test.go
- pkg/db/db.go
- pkg/db/testdata/fixtures/multiple-buckets.yaml
- pkg/vulnsrc/vulnerability/const.go
Use ecosystem names instead of languages as a bucket prefix.
- nodejs => npm
- php => composer
- python => pip
- ruby => rubygems
- rust => cargo
> fix: rename bucket prefixes

- .github/workflows/cron.yml
The Makefile targets were renamed in this PR https://github.com/aquasecurity/trivy-db/pull/65 but the github cron workflow is trying to call the old one and failing.
fixes #87
> Fix github cron workflow

- pkg/vulnsrc/vulnerability/const.go
Replace https://github.com/aquasecurity/trivy-db/pull/83
> Added dotnet as a constant in vulnerability sources.

- pkg/vulnsrc/vulnerability/const.go
Replace dotnet with nuget to align with GitHub Advisory Database.
https://github.com/advisories
> fix: replace dotnet with nuget

- pkg/types/types.go
I've added the deprecated label to `Severity` by mistake. `Severity` is not filled in `trivy-db`, but is supposed to be selected from `VendorSeverity` depending on a scan target in `trivy`. If `trivy` scans a `debian:9` image, `Severity` should be Debian's one. In short, this field is necessary.
> refactor: update a comment

- pkg/vulnsrc/ghsa/ghsa.go
- pkg/vulnsrc/ghsa/ghsa_test.go
Fixed this case. 
```
| CVE-2020-8840    |          |                   | 2.9.10.3, 2.8.11.5, , , , , ,  | jackson-databind: Lacks certain       |
|                  |          |                   | , ,                            | xbean-reflect/JNDI blocking           |
|                  |          |                   |                                | -->avd.aquasec.com/nvd/cve-2020-8840  |
```
GHSA FirstPatchedVersion.Identifier is possible empty.
https://github.com/advisories/GHSA-gww7-p5w4-wrfv
> fix(ghsa): empty patched version

- pkg/vulnsrc/redhat/redhat.go
From Red Hat website
>My product is listed as "Out of Support Scope". What does this mean?
>When a product is listed as "Out of Support Scope", it means a vulnerability with the impact level assigned to this CVE is no longer covered by its current support lifecycle phase. The product has been identified to contain the impacted component, but analysis to determine whether it is affected or not by this vulnerability was not performed. The product should be assumed to be affected. Customers are advised to apply any mitigation options documented on this page, consider removing or disabling the impacted component, or upgrade to a supported version of the product that has an update available.
> feat(redhat): add Out of support scope

- pkg/vulnsrc/debian/debian.go
Adds `debian 11`/`bullseye` to the `debian` source, ahead of the future release scheduled for 2021-08-14 ([click here for announcement](https://lists.debian.org/debian-devel-announce/2021/07/msg00003.html)).
<details>
<summary>pre</summary>
<p>
```shell
$ trivy image debian:bullseye-slim@sha256:9bfa0f4fb6d32116de4a6172f89a9266f7c73d1b8dae46f765bed703e541175e
2021-08-08T06:22:59.992-0400	INFO	Detected OS: debian
2021-08-08T06:22:59.992-0400	INFO	Detecting Debian vulnerabilities...
2021-08-08T06:22:59.992-0400	INFO	Number of language-specific files: 0
debian:bullseye-slim@sha256:9bfa0f4fb6d32116de4a6172f89a9266f7c73d1b8dae46f765bed703e541175e (debian 11.0)
==========================================================================================================
Total: 0 (UNKNOWN: 0, LOW: 0, …
```
> add debian bullseye

- pkg/vulnsrc/ghsa/ghsa.go
- pkg/vulnsrc/ghsa/ghsa_test.go
Skipping the advisories from GitHub Advisory Database which marked as "Withdrawn".
Fix https://github.com/aquasecurity/trivy/issues/1188
> fix: ignore withdrawn advisories

- pkg/vulnsrc/bundler/bundler.go
OSVDB doesn't allow commercial usage without agreement.
Skipping OSVDB* files so that Trivy can be used in commercials.
also remove the defunct `osvdb.org` website from URL.
Fixes [aquasecurity/trivy/#1208](https://github.com/aquasecurity/trivy/issues/1208)
> fix(ruby): remove advisories from OSVDB

- pkg/vulnsrc/python/python.go
Some advisories in safety-db have the prefix of "PVE-" and it doesn't make sense. We should use pyup id in that case.
> fix(safety-db): use pyup id instead of PVE-ID

- .github/workflows/cron-gh-releases.yml
- .github/workflows/cron.yml
We move Trivy DB from GitHub Releases to GitHub Packages Container registry. There are many benefits.
- Tagging like container images
- Trivy client easily switch schema versions. For instance, ghcr.io/aquasecurity/trivy-db:v1 to ghcr.io/aquasecurity/trivy-db:v2. It is really helpful when we add breaking change.
- No need GITHUB_TOKEN
- Organizations who download Trivy DB from GitHub Releases many times currently need to set GITHUB_TOKEN for rate limiting. GHCR doesn't need it at the moment.
- Update the same tag
- GitHub Releases doesn't support replacing assets in the same tag/release. That's why we needed to create a unique tag/release such as `v1-2021110312` every time. See [Releases](https://github.com/aquasecurity/trivy-db/releases). It is a workaround.
- GHCR allows it so that we …
> chore: move to GitHub Packages Container registry

- Dockerfile
The job is failing now due to the old Go version in Dockerfile.
https://github.com/aquasecurity/trivy-db/runs/4589164324?check_suite_focus=true
> chore: bump up Go to 1.17

- .github/workflows/cron.yml
`db-fetch-vuln-list-main` no longer exists. Fix the following error.
https://github.com/aquasecurity/trivy-db/actions/runs/1662893170
> chore(release): rename the target name

- pkg/vulnsrc/debian/debian.go
- pkg/vulnsrc/debian/debian_test.go
- pkg/vulnsrc/debian/testdata/fixtures/debian.yaml
We migrated Debian from OVAL to SALSA.
https://github.com/aquasecurity/trivy-db/pull/137
Debian OVAL buckets are no longer needed, but it's been kept for backward compatibility. We can remove it in v2.
https://github.com/aquasecurity/trivy-db/pull/168
> refactor(debian): remove oval buckets

- pkg/utils/utils.go
- pkg/vulnsrc/alma/alma.go
- pkg/vulnsrc/amazon/amazon.go
- pkg/vulnsrc/rocky/rocky.go
- pkg/vulnsrc/rocky/rocky_test.go
- pkg/vulnsrc/rocky/testdata/happy/vuln-list/rocky/8/BaseOS/x86_64/2021/RLSA-2021-1989.json
- pkg/vulnsrc/rocky/testdata/modular/vuln-list/rocky/8/BaseOS/x86_64/2021/RLSA-2021-1979.json
- pkg/vulnsrc/rocky/testdata/sad/vuln-list/rocky/8/BaseOS/x86_64/2021/RLSA-2021-1989.json
- pkg/vulnsrc/rocky/types.go
- pkg/vulnsrc/vulnerability/const.go
- pkg/vulnsrc/vulnerability/vulnerability.go
- pkg/vulnsrc/vulnsrc.go
This PR(https://github.com/aquasecurity/vuln-list-update/pull/107) adds Rocky Linux to the vuln-list.
So, let's add Rocky Linux to trivy-db.
```console
$ ./trivy-db build --cache-dir ~/.cache/vuln-list-update --only-update rocky
2021/09/22 13:42:57 Updating vulnerability database...
2021/09/22 13:42:57 Updating rocky data...
```
refs. https://github.com/aquasecurity/trivy/issues/1053
Need to merge the below PRs first
- https://github.com/aquasecurity/vuln-list-update/pull/107
> feat(rocky): support Rocky Linux

- pkg/db/vulnerability.go
When a vulnerability does not exist in the vulnerabilities bucket, `bucket.Get` returns an empty byte array, which cannot be parsed by `json.Unmarshal`. This causes warnings to appear in the Trivy output for vulnerabilities which don't have an item in the `vulnerabilities` bucket. 
```
$ trivy i registry.gitlab.com/gitlab-org/security-products/dast/webgoat-8.0@sha256:bc09fe2e0721dfaeee79364115aeedf2174cce0947b9ae5fe7c33312ee019a4e | head -n 28
2022-02-14T08:22:03.170-0600    INFO    Detected OS: debian
2022-02-14T08:22:03.170-0600    INFO    Detecting Debian vulnerabilities...
2022-02-14T08:22:03.184-0600    INFO    Number of language-specific files: 1
2022-02-14T08:22:03.184-0600    INFO    Detecting jar vulnerabilities...
2022-02-14T08:22:03.189-0600    WARN    Error while getting …
```
> Improve error messaging when vulnerability details are missing

- pkg/vulnsrc/suse-cvrf/suse-cvrf.go
Method `Name()` of `VulnSrc` returns the same `SourceID`("suse-cvrf") for all SUSE sources.
Return "opensuse-cvrf" for openSUSE.
Fixes #193
> fix(suse): added vulnerabilities for SUSE Enterprise Server

- pkg/vulnsrc/ubuntu/ubuntu.go
Added support [Ubuntu ESM versions](https://ubuntu.com/security/esm).
ESM versions format is `{version}-ESM`. e.g.: `14.04-ESM`
> feat(ubuntu): added Ubuntu ESM versions

- .github/workflows/go.yml
- go.mod
- go.sum
- pkg/vulnsrc/ghsa/ghsa.go
- pkg/vulnsrc/redhat/redhat.go
Bump [golangci-lint](https://github.com/golangci/golangci-lint) from v1.41 to v1.45.2.
`Strings.Title` function [has been deprecated](https://pkg.go.dev/strings#Title). This linter error has been fixed.
> chore(deps): bump golangci-lint from 1.41 to 1.45.2

- pkg/vulnsrc/glad/glad.go
Now advisories from GLAD without CVE-ID are defined via GHSA-ID (if they have it), so `trivy-db` has to support prefix `GHSA`.
> feat: add support GHSA prefix for GitLab

- pkg/types/types.go
- pkg/vulnsrc/redhat-oval/redhat-oval.go
- pkg/vulnsrc/redhat-oval/redhat-oval_test.go
- pkg/vulnsrc/redhat-oval/testdata/fixtures/happy.yaml
- pkg/vulnsrc/redhat-oval/types.go
RedHat Oval database may contain advisories with same `package name` and `affected cpe list` but with different architectures.
We can get false positive for this packages.
These packages should be separated.
For this `Arch` field [was added](https://github.com/aquasecurity/trivy-db/compare/main...DmitriyLewen:feat/rpm-oval-arch?expand=1#diff-8e49337a1417a39a62ebf427e84fb2faa566c96e37ae627ac484c05dbe65c483R103) to types.Advisory structure.
Example:
`RHSA-2016:2098` and `RHSA-2017:0372` advisories have same package name(`kernel`), affected cpe list( `cpe:/o:redhat:enterprise_linux:7`), but different architectures(`ppc64|ppc64le|s390x|x86_64` and `aarch64`)
- [RHSA-2016:2098](https://www.redhat.com/security/data/oval/com.redhat.rhsa-20162098.xml): 
```xml
...
<affected_cpe_list> …
```
> feat(rpm): added arch field to db

- pkg/vulnsrc/redhat-oval/testdata/fixtures/happy.yaml
- pkg/vulnsrc/redhat-oval/types.go
Json tag for `Entry.Arches` has been renamed from `Arch` to `Arches`
> fix(redhat-oval): changed tag for Entry.Arches

- pkg/vulnsrc/vulnerability/vulnerability.go
There are Go packages with names that contain letters in different cases, eg: `github.com/Masterminds/vcs`.
we shouldn't normalize them.
> fix(go): no lowercase for go packages

- pkg/vulnsrc/alma/alma.go
There are advisories with empty title field. For example: [ALSA-2022:0951](https://github.com/aquasecurity/vuln-list/blob/619fcebb428ad494d58355c38a5acbfb42d12a6c/alma/8/2022/ALSA-2022:0951.json#L94-L95).
`ID` field is always fill.
Use [Reference.ID](https://github.com/aquasecurity/trivy-db/blob/930461748b6307590f4718daeab37cec51fe78b3/pkg/vulnsrc/alma/types.go#L64) field to get cve-id.
> fix(alma): use id field to get cve-id

- pkg/vulnsrc/amazon/amazon.go
- pkg/vulnsrc/amazon/amazon_test.go
- pkg/vulnsrc/amazon/testdata/happy/vuln-list/amazon/2022/ALAS2022-2021-003.json
Add advisories for Amazon Linux 2022
> feat(amazon linux): add 2022 version support

- pkg/vulnsrc/govulndb/govulndb.go
- pkg/vulnsrc/govulndb/govulndb_test.go
comparion of zero (0) version is failing with 0.0.0-<timestamp>-<commit> type versions.
> bugfix: handle zero version event

- pkg/vulnsrc/suse-cvrf/suse-cvrf.go
- pkg/vulnsrc/suse-cvrf/suse-cvrf_test.go
As shown in the image, keys with unexpected OS Version such as `SUSE Linux Enterprise 11-PUBCLOUD` and `SUSE Linux Enterprise 5.0` are registered.
This PR fixes it.
> fix(suse): fix getOSVersion

- pkg/vulnsrc/bucket/bucket.go
- pkg/vulnsrc/ghsa/ghsa.go
- pkg/vulnsrc/ghsa/ghsa_test.go
- pkg/vulnsrc/ghsa/testdata/happy/vuln-list/ghsa/rust/time/GHSA-wcg3-cvx6-7396.json
- pkg/vulnsrc/osv/osv.go
- pkg/vulnsrc/osv/osv_test.go
- pkg/vulnsrc/vulnerability/const.go
Trivy DB should contain data from GitHub Advisory Database for Rust ecosystem: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Arust
> feat: add Rust ecosystem from GHSA and disable from OSV

- pkg/vulnsrc/vulnerability/const.go
- pkg/vulnsrc/vulnsrc.go
- pkg/vulnsrc/wolfi/testdata/happy/vuln-list/wolfi/binutils.json
- pkg/vulnsrc/wolfi/testdata/sad/vuln-list/wolfi/binutils.json
- pkg/vulnsrc/wolfi/types.go
- pkg/vulnsrc/wolfi/wolfi.go
- pkg/vulnsrc/wolfi/wolfi_test.go
This PR follows up https://github.com/aquasecurity/vuln-list-update/pull/183 and adds support for the Wolfi secdb data to be included in Trivy's vulnerability database file.
Related to https://github.com/aquasecurity/trivy/issues/3205
> feat(wolfi): add support for Wolfi Linux

- pkg/vulnsrc/bucket/bucket.go
- pkg/vulnsrc/ghsa/ghsa.go
- pkg/vulnsrc/ghsa/ghsa_test.go
- pkg/vulnsrc/ghsa/testdata/happy/vuln-list/ghsa/pub/http/GHSA-4rgh-jx4f-qfcq.json
- pkg/vulnsrc/vulnerability/const.go
Add `pub` ecosystem for `Dart`
Required to merge [#186](https://github.com/aquasecurity/vuln-list-update/pull/186) first.
> feat(ghsa): add pub ecosystem

- .github/workflows/cron.yml
- .github/workflows/go.yml
Node 12 has been out of support since April 2022, so Node.js 12 actions are deprecated.
we should update the actions (actions/setup-go@v2, actions/checkout@v2, docker/login-action@v1) to use Node.js 16.
Also `save-state` and `set-output` commands are deprecated now, so all actions should be updated for using `@actions/core` package v1.10.0 or greater.
Before:
After:
> ci: update deprecated GitHub Actions with Node 12 and `save-state` command

- pkg/vulnsrc/amazon/amazon.go
Add `Amazon Linux 2023` support.
merge this PR first!
> feat(amazon): add amazon linux 2023 support

- README.md
People are still confused about the following two things.
- Trivy DB is hosted on GHCR, not GitHub Releases
- `docker pull` doesn't work
This PR adds notices.
> docs: add more notices

- pkg/db/db.go
Slices returned by Bolt's Get and ForEach are only valid while the transaction is open (this is documented for example at https://github.com/etcd-io/bbolt#foreach). The return values of `get` and `forEach` in `db.go` were thus unsafe; using them for example json unmarshalling in `GetAdvisories` lead to panics (segmentation violations).
This is unlikely to happen when used as part of a one-time CLI, but happened regularly when used as part of a long-running service.
Note: we fixed this issue internally a few weeks ago (no occurence of panics since then), and haven't kept the stack traces around to create an issue unfortunately (not that they were particularly helpful, as the code at the root of the issue wasn't part of the trace).
> Fix panics caused by keeping unsafe byte arrays returned by Bolt

- .github/workflows/cron.yml
This pull request updates the github workflow to use oras version 1.0.0, I believe the bugs that were preventing an upgrade have now been resolved.  see [oras issue #447](https://github.com/oras-project/oras/issues/447).
This pull request also updates the syntax used to push the OCI artifact. Using /dev/null as the source for the config results in a zero (0) length blob, this causes an error when using `oras copy` to  copy the artifact to another v2 API registry. Using the new `--artifact-type` parameter creates a config of the given type, containing an empty json object `{}`, and allows for the artifact to be copied successfully.
These changes are necessary to allow the trivy db OCI artifact to be copied to a registry hosted on an air-gapped network.
> upgrade to oras 1.0.0 and fix issue with 0 length config

- pkg/vulnsrc/ubuntu/ubuntu.go
Ubuntu 23.04's code name is Lunar Lobster - see https://wiki.ubuntu.com/Releases.
> feat(ubuntu): support Ubuntu 23.04

- pkg/vulnsrc/redhat-oval/redhat-oval.go
- pkg/vulnsrc/redhat-oval/redhat-oval_test.go
- pkg/vulnsrc/redhat-oval/testdata/fixtures/data-source.yaml
Fill `DataSource` field in advisories from [Get](https://github.com/aquasecurity/trivy-db/blob/6e8ee5a37ad994f13ef21d69cbe1d0ec7a8b0539/pkg/vulnsrc/redhat-oval/redhat-oval.go#L245) function.
> feat(redhat-oval): fill DataSource field in Advisories from Get function

- Makefile
- pkg/vulnsrc/vulnsrc.go
See https://github.com/aquasecurity/vuln-list-update/pull/229
Also, this PR drops Arch Linux since Trivy doesn't support it.
> chore: fall back into vuln-list-reserve

- Makefile
`tar` in `ubuntu` image can't unpack `zip` archive - https://github.com/aquasecurity/trivy-db/actions/runs/6010476045/job/16301974826#step:5:16.
Use `master.tar.gz` for CocoaPods Specs
Remove `db-all` command to avoid cases, when new changes are added only to this command.
> fix(ci): download tar.gz archive for CocoaPods Specs

- pkg/vulnsrc/ghsa/ghsa.go
- pkg/vulnsrc/ghsa/ghsa_test.go
- pkg/vulnsrc/ghsa/testdata/happy/ghsa/advisories/github-reviewed/2021/08/GHSA-mp6f-p9gp-vpj9/GHSA-mp6f-p9gp-vpj9.json
- pkg/vulnsrc/vulnerability/const.go
After #345 changes we addув check of ecosystems for OSV - https://github.com/aquasecurity/trivy-db/blob/d5388c99ca492bf0c8822b27a2e5190794543bb5/pkg/vulnsrc/osv/osv.go#L143-L146 
GHSA uses `Rust`ecosystem -https://github.com/aquasecurity/trivy-db/blob/d5388c99ca492bf0c8822b27a2e5190794543bb5/pkg/vulnsrc/ghsa/ghsa.go#L32
OSV uses `Cargo` ecosystem - https://github.com/aquasecurity/trivy-db/blob/d5388c99ca492bf0c8822b27a2e5190794543bb5/pkg/vulnsrc/osv/osv.go#L345-L346
That is why we don't save Rust advisories.
Result DB:
> fix(ghsa): return Rust advisories 

- pkg/vulnsrc/bitnami/bitnami_test.go
- pkg/vulnsrc/bucket/bucket.go
- pkg/vulnsrc/bucket/bucket_test.go
- pkg/vulnsrc/bundler/bundler.go
- pkg/vulnsrc/composer/composer.go
- pkg/vulnsrc/glad/glad.go
- pkg/vulnsrc/node/node.go
- pkg/vulnsrc/osv/osv.go
Using `types.Ecosystem` prevents misuse of the first argument of bucket.Name.
> refactor: use types.Ecosystem in bucket.Name()

- pkg/vulnsrc/ubuntu/ubuntu.go
Ubuntu 23.10's code name is Mantic Minotaur - see https://wiki.ubuntu.com/Releases.
> feat(ubuntu): support Ubuntu 23.10

- pkg/types/types.go
- pkg/vulnsrc/rocky/rocky.go
Added handling for Custom and Erratum fields
Resolves: #369
> fix rocky: multi-arch support broke backward compatibility

- pkg/vulnsrc/amazon/amazon.go
- pkg/vulnsrc/amazon/testdata/happy/vuln-list/amazon/1/ALAS-2018-1093.json
Severity for `amazon` advisories is not always in lower case:
[Important](https://github.com/aquasecurity/vuln-list/blob/71ec42935249865020c560fb8e2cbe4606b00280/amazon/2023/ALAS2023-2023-297.json#L10)
[important](https://github.com/aquasecurity/vuln-list/blob/71ec42935249865020c560fb8e2cbe4606b00280/amazon/2/ALAS2-2023-2224.json#L10)
- Close aquasecurity/trivy/issues/5762
> fix(amazon): compare severity in lower case

- .github/workflows/cron.yml
cache dir size is 12GB:
```
➜ du -sh ./cache 
12G    ./cache
➜ make db-build
...
➜ du -sh ./cache/db 
2.7G	./cache/db
➜ du -sh ./cache   
16G	./cache
```
So we need move space to build, compact and compress db.
Add `maximize-build-space`.
> ci: use maximize-build-space

- pkg/vulnsrc/debian/debian.go
- pkg/vulnsrc/debian/debian_test.go
- pkg/vulnsrc/debian/testdata/happy/vuln-list-debian/tracker/CVE/CVE-2023-5981.json
- pkg/vulnsrc/debian/testdata/happy/vuln-list-debian/tracker/source/bullseye/main/g/gnutls28.json
Fix for https://github.com/aquasecurity/trivy-db/issues/380
> Fix issue 380

- pkg/vulnsrc/ghsa/ghsa.go
- pkg/vulnsrc/ghsa/ghsa_test.go
- pkg/vulnsrc/ghsa/testdata/happy/ghsa/advisories/github-reviewed/2023/04/GHSA-32qq-m9fh-f74w/GHSA-32qq-m9fh-f74w.json
- pkg/vulnsrc/osv/osv.go
- pkg/vulnsrc/osv/types.go
There two cases when `GHSA` uses `last_known_affected_version_range` field - https://github.com/github/advisory-database/issues/470#issuecomment-1998604377.
We need to add version for case when `last_known_affected_version_range field` is exist and `fixed`/`last_affected` field doesn't exist.
- Close #391
> fix(ghsa): add support of `last_known_affected_version_range` field

- pkg/vulnsrc/suse-cvrf/suse-cvrf.go
- pkg/vulnsrc/suse-cvrf/suse-cvrf_test.go
- pkg/vulnsrc/suse-cvrf/testdata/happy/openSUSE Tumbleweed/vuln-list/cvrf/suse/opensuse/openSUSE-SU-2024-10400-1.json
(Tumbleweed has no version as it is rolling)
https://github.com/aquasecurity/trivy-db/issues/410
> added openSUSE Tumbleweed version detection

- pkg/utils/strings/strings.go
- pkg/vulnsrc/amazon/amazon.go
- pkg/vulnsrc/debian/debian.go
- pkg/vulnsrc/oracle-oval/oracle-oval.go
- pkg/vulnsrc/rocky/rocky.go
- pkg/vulnsrc/ubuntu/ubuntu.go
In this commit, we replace `utils/strings/InSlice` function with the built-in `slices.Contains` function which is supported in go 1.18+ and it would work with the current project go version `1.19` as appears in the `go.mod` file.
Closes #245
I've run the test cases using `make test` and all of them passed.
> pkg: replace `utils/strings/InSlice` func with `slices.Contains`

- .gitignore
- Makefile
- pkg/app.go
- pkg/build.go
- pkg/db/db.go
- pkg/dbtest/init.go
- pkg/metadata/metadata.go
- pkg/vulndb/db.go
- pkg/vulndb/db_test.go
Currently, the [db](https://github.com/aquasecurity/trivy-db/blob/27fa703f5ffa3893729ffc84a9b096f3406eebf2/pkg/db/db.go#L89) and [metadata](https://github.com/aquasecurity/trivy-db/blob/27fa703f5ffa3893729ffc84a9b096f3406eebf2/pkg/metadata/metadata.go#L38) packages are passed a cache directory, within which they create subdirectories like `$CACHE_DIR/db`. This results in database and metadata files being stored at paths such as:
- `$CACHE_DIR/db/trivy.db`
- `$CACHE_DIR/db/metadata.json`
While the metadata implementation and other aspects are common and potentially reusable for Java DB and other databases, the hard-coded `db/` subdirectory makes it difficult to reuse these packages effectively.
To improve reusability, I propose to remove the hard-coded `db/` subdirectory and instead allow …
> refactor(metadata): pass db dir

- Makefile
The directories can be passed now.
```
$ make db-fetch-vuln-list CACHE_DIR=/path/to/cache
```
> chore: configure directories in Makefile

- pkg/vulnsrc/suse-cvrf/suse-cvrf.go
- pkg/vulnsrc/suse-cvrf/suse-cvrf_test.go
- pkg/vulnsrc/suse-cvrf/testdata/happy/SUSE Linux Enterprise Micro/vuln-list/cvrf/suse/suse/SUSE-SU-2024-2546-1.json
https://github.com/aquasecurity/trivy/issues/7221
> feat(slemicro): enable SUSE Linux Enterprise Micro

- pkg/vulnsrc/redhat-oval/redhat-oval.go
- pkg/vulnsrc/redhat-oval/redhat-oval_test.go
`Get()` function returns an error if the CPE is not found
> refactor(redhat-oval): return an error if the CPE is not found

- pkg/types/status.go
In MarshalJSON, using a pointer receiver was not supposed to be marshalled correctly, but in Trivy, the output was correct (I did not investigate the reason in detail), and furthermore, to suppress the following warning, I used a pointer.
>Struct Status has methods on both value and pointer receivers. Such usage is not recommended by the Go Documentation. 
However, it seems that `Status` was only correctly marshalled by chance because [DetectedVulnerability](https://github.com/aquasecurity/trivy/blob/7aea79dd93cfb61453766dbbb2e3fc0fbd317852/pkg/types/report.go#L114) was a slice. We actually found a case where `DetectedVulnerability` was [not correctly marshalled](https://github.com/aquasecurity/trivy/pull/7463) when `DetectedVulnerability` was not a slice, so this PR will correct this. …
> fix: do not use a pointer receiver for Status.MarshalJSON

- Makefile
This PR changes to have clients download the DB once a day as we are facing [GHCR rate limits](https://github.com/aquasecurity/trivy/discussions/7538). However, the DB will be built [once every 6 hours](https://github.com/aquasecurity/trivy-db/blob/cfa337a1088bbcee598ab93656c83fe6b9acb946/.github/workflows/cron.yml#L5).
> ci: set to download DB daily

- .github/workflows/cron.yml
`ubuntu-24.04` runner is now `latest` runner.
But `ubuntu-24.04` runner doesn't have preinstalled `oras` - https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md#cli-tools
Before using `ubuntu-24.04` - we used `ubuntu-22.04`.
`ubuntu-22.04` contains [oras v1.2.0](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#cli-tools).
Changes of this PR:
- pin `ubuntu-24.04` runner (to avoid problem with next update `latest` runner).
- bump installed `oras` version to `v1.2.0` (as in `ubuntu-22.04` runner)
- use installed `oras`.
test run - https://github.com/DmitriyLewen/trivy-db/actions/runs/11339374413/job/31534396989
> fix(cron): pin `ubuntu-24.04` runner and use installed (bump to v1.2.0) `oras` version

- README.md
We [changed](https://github.com/aquasecurity/trivy-db/pull/444) update interval to 24 hours.
So we need to update the README about that.
> docs: update info about update interval

- pkg/vulnsrc/azure/azure.go
- pkg/vulnsrc/azure/azure_test.go
- pkg/vulnsrc/azure/oval/types.go
- pkg/vulnsrc/azure/testdata/happy/vuln-list/azure/3.0/definitions/2018/38656-1.json
- pkg/vulnsrc/azure/testdata/happy/vuln-list/azure/3.0/definitions/2023/38611-1.json
- pkg/vulnsrc/azure/testdata/happy/vuln-list/azure/3.0/definitions/2023/52881-2.json
- pkg/vulnsrc/azure/testdata/happy/vuln-list/azure/3.0/objects/objects.json
- pkg/vulnsrc/azure/testdata/happy/vuln-list/azure/3.0/states/states.json
- pkg/vulnsrc/azure/testdata/happy/vuln-list/azure/3.0/tests/tests.json
- pkg/vulnsrc/azure/testdata/happy/vuln-list/mariner/2.0/definitions/2021/7412.json
- pkg/vulnsrc/azure/testdata/happy/vuln-list/mariner/2.0/definitions/2023/31872-1.json
- pkg/vulnsrc/azure/testdata/happy/vuln-list/mariner/2.0/definitions/2023/31880-1.json
- pkg/vulnsrc/azure/testdata/not-applicable-definition/vuln-list/mariner/2.0/definitions/2013/6640.json
- pkg/vulnsrc/azure/testdata/sad/criterion-is-not-array/vuln-list/mariner/1.0/definitions/2008/3173.json
- pkg/vulnsrc/azure/testdata/sad/criterion-is-not-array/vuln-list/mariner/1.0/objects/objects.json
- pkg/vulnsrc/azure/testdata/sad/criterion-is-not-array/vuln-list/mariner/1.0/states/states.json
- pkg/vulnsrc/azure/testdata/sad/criterion-is-not-array/vuln-list/mariner/1.0/tests/tests.json
- pkg/vulnsrc/azure/testdata/sad/empty-stateref-tests/vuln-list/mariner/1.0/definitions/2008/3173.json
- pkg/vulnsrc/azure/testdata/sad/empty-testref-definition/vuln-list/mariner/1.0/definitions/2008/3173.json
`azure` has started using `criterion` as array.
See #468 for more details.
This PR updates logic to parse `criterion` as array.
Test trivy-db build - https://github.com/DmitriyLewen/trivy-db/actions/runs/11833760212/job/32973071628
- Close #468
- aquasecurity/vuln-list-update/pull/313
> fix(azure): multiple criterions

- pkg/build.go
- pkg/db/db.go
Currently the `trivy.db` file in the OCI artifact is set to be readable only by the `runner` user that created the file, unlike the `metadata.json` file:
```
$ crane export public.ecr.aws/aquasecurity/trivy-db:2 > trivy-db.tar
$ tar -tvf trivy-db.tar
-rw-------  0 runner docker 564006912 Nov 18 10:17 trivy.db
-rw-r--r--  0 runner docker       143 Nov 18 10:17 metadata.json
```
This is different from the `trivy-java.db` file:
```
$ crane export public.ecr.aws/aquasecurity/trivy-java-db:1 > trivy-java-db.tar
$ tar -tvf trivy-java-db.tar
-rw-r--r--  0 runner docker 1122304000 Nov 17 19:41 trivy-java.db
-rw-r--r--  0 runner docker        143 Nov 17 19:41 metadata.json
```
This PR modifies the default mode to be `0644` when built via this repository/GitHub actions runner, matching the Java DB …
> fix: set trivy.db file to be world-readable

- pkg/db/db.go
Address the feedback/missed change on #471 added after the PR was merged: https://github.com/aquasecurity/trivy-db/pull/471#discussion_r1847764433
> fix: set trivy.db file to be world-readable (follow-up)

- cmd/trivy-db/main.go
- go.mod
- go.sum
- pkg/db/db.go
- pkg/log/log.go
- pkg/utils/file.go
- pkg/utils/time.go
- pkg/vulndb/db.go
- pkg/vulnsrc/alma/alma.go
- pkg/vulnsrc/amazon/amazon.go
- pkg/vulnsrc/azure/azure.go
- pkg/vulnsrc/debian/debian.go
- pkg/vulnsrc/ghsa/cocoapods.go
- pkg/vulnsrc/glad/glad.go
- pkg/vulnsrc/glad/glad_test.go
- pkg/vulnsrc/nvd/nvd.go
- pkg/vulnsrc/oracle-oval/oracle-oval.go
- pkg/vulnsrc/osv/osv.go
- pkg/vulnsrc/photon/photon.go
- pkg/vulnsrc/redhat-oval/redhat-oval.go
- pkg/vulnsrc/redhat/redhat.go
- pkg/vulnsrc/rocky/rocky.go
- pkg/vulnsrc/suse-cvrf/suse-cvrf.go
- pkg/vulnsrc/suse-cvrf/suse-cvrf_test.go
- pkg/vulnsrc/ubuntu/ubuntu.go
- pkg/vulnsrc/vulnerability/vulnerability.go
This PR replaces `log` with `log/slog` and standardizes the logger implementation across vulnerability source packages by introducing a consistent logging pattern with source-specific prefixes.
- Replace direct usage of `log` with `github.com/aquasecurity/trivy-db/pkg/log`
- Embed `*log.Logger` in `VulnSrc` structs
- Implement source-specific prefixes for each vulnerability source using `log.WithPrefix()`
- Standardize logging method calls (e.g., `vs.Info()`, `vs.Warn()`) across all sources
1. Improved log clarity:
- Each log message is clearly tagged with its source
- Easier to identify and debug source-specific issues
- Better log filtering capabilities
2. Enhanced maintainability:
- Consistent logging patterns across all vulnerability sources
- Centralized logging configuration through …
> refactor: use slog

- pkg/vulnsrc/vulnerability/const.go
- pkg/vulnsrc/vulnerability/vulnerability.go
Add `AllSourceIDs` with list of all sourceIDs.
This is required for aquasecurity/trivy/issues/8180
> refactor: add `AllSourceIDs`

- pkg/db/db.go
- pkg/db/db_test.go
if `bbolt` returned panic when initializing db we just create new empty database.
This results in Trivy doesn't show vulnerabilities.
See https://github.com/aquasecurity/trivy/discussions/7758#discussioncomment-12309744
we should return error if we couldn't open trivy-db
example (https://gist.github.com/knqyf263/7ce8e504b6d1f9867e6898f83c89acba is used to reproduce error):
before:
```
Testing race condition with downloader.Download
Starting concurrent downloads to the same destination file...
Download 1: Adding fixed delay of 100 ms
Download 0: Starting
Download 1: Starting
Download 0: Completed
Download 1: Completed
Checking the destination file:
File: /var/folders/8m/p1341n2941jbyc5gm7357x5c0000gn/T/trivy-poc-1180293935/dst/trivy.db, Size: 65536 bytes
WARNING - DB is EMPTY!
Result: …
```
> fix(db): return error if panic occurs when opening database

- pkg/vulnsrc/ubuntu/ubuntu.go
Add ubuntu 18.04 ESM into trivy-db
`ubuntu` uses `esm-infra/bionic` name - https://github.com/aquasecurity/vuln-list/blob/e7622a9b8f3ff5c1c958f4846173c64aed270340/ubuntu/2023/CVE-2023-2953.json#L35-L38
EXample:
Actual DB:
```
➜  trivy -q image ubuntu:18.04-esm -f json | grep Results -A 5
"Results": [
{
"Target": "ubuntu:18.04-esm (ubuntu 18.04-ESM)",
"Class": "os-pkgs",
"Type": "ubuntu"
}
```
New DB:
```bash
➜  trivy -q image ubuntu:18.04-esm -f json | grep Results -A 5
"Results": [
{
"Target": "ubuntu:18.04-esm (ubuntu 18.04-ESM)",
"Class": "os-pkgs",
"Type": "ubuntu",
"Vulnerabilities": [
```
> feat(ubuntu): add ubuntu 18 ESM support

- .github/workflows/cron.yml
`Skitionek/notify-microsoft-teams` fixed the issue and now we can use it instead of the fork
See - https://github.com/aquasecurity/notify-microsoft-teams/pull/1
test run - https://github.com/DmitriyLewen/trivy-db/actions/runs/14485778659/job/40630965075
> ci: use `Skitionek/notify-microsoft-teams` instead of aquasecurity fork

- pkg/vulnsrc/suse-cvrf/suse-cvrf.go
- pkg/vulnsrc/suse-cvrf/suse-cvrf_test.go
This PR adds a branch to the `getOSVersion` function that parses the openSUSE Leap Micro strings.
Fixes #367
> Parse openSUSE Leap Micro versions

- README.md
The instructions for running `trivy-db` locally used `//` which are not shell comments. Replace with `#` which will safely ignore anything after. This will allow the code snippet to be copied across onto a local developer's machine successfully.
> fix(docs): Update README.md to use appropriate shell commenting

- pkg/vulnsrc/alpine/alpine.go
- pkg/vulnsrc/alpine/alpine_test.go
- pkg/vulnsrc/alpine/testdata/happy/vuln-list/alpine/ansible.json
There are advisories with a vulnerability ID other than CVE-ID (e.g. GHSA-ID):
e.g. https://security.alpinelinux.org/srcpkg/vaultwarden
```
➜ grep -r "GHSA*" | grep -v CVE | sort -u
./3.10/main/squid.json:      "GHSA-572g-rvwr-6c7f"
./3.11/main/squid.json:      "GHSA-572g-rvwr-6c7f"
./3.12/main/squid.json:      "GHSA-572g-rvwr-6c7f"
./3.13/community/py3-bleach.json:      "GHSA-vv2x-vrpj-qqpq"
./3.13/main/glib.json:      "GHSL-2021-045",
./3.13/main/squid.json:      "GHSA-572g-rvwr-6c7f"
./3.14/community/py3-bleach.json:      "GHSA-vv2x-vrpj-qqpq"
./3.14/main/squid.json:      "GHSA-572g-rvwr-6c7f"
./3.15/community/py3-treq.json:      "GHSA-fhpf-pp6p-55qc"
./3.16/community/py3-treq.json:      "GHSA-fhpf-pp6p-55qc"
./3.17/community/py3-treq.json:      "GHSA-fhpf-pp6p-55qc" …
```
> fix(alpine): save not only CVE-IDs

- README.md
Hello,
The link oras cli is 404 like declared in the issue #402,
If we check an archived page we find the good page : https://web.archive.org/web/20230315183929/https://oras.land/cli/ 
after the page is always 404 ex: https://web.archive.org/web/20230829061007/https://oras.land/cli/
Thanks to apply this commit :) 
Have nice day
> docs(oras): #402 fix link oras install

- pkg/vulnsrc/ubuntu/ubuntu.go
This is to resolve first part of an issue here: <https://github.com/aquasecurity/trivy/issues/8980>
I tried for a while on my own, and looked through a few past PRs adding support for new OS/new versions, but couldn't figure out how to confirm that the new trivy-db contains advisories for Ubuntu 25.04.
I did find some 25.04 related CVEs in the cache, but I reckon that is just what's been downloaded from the online Ubuntu CVE database?
> feat(ubuntu): Add support for Ubuntu plucky (25.04)

- pkg/db/advisory.go
- pkg/db/advisory_test.go
- pkg/db/testdata/fixtures/data-source.yaml
- pkg/types/types.go
- pkg/vulnsrc/rootio/rootio.go
- pkg/vulnsrc/rootio/rootio_test.go
- pkg/vulnsrc/rootio/testdata/fixtures/data-source.yaml
We added baseOS suffixes for `Root.io` advisories in #554.
But after [this discussion](https://github.com/aquasecurity/trivy/pull/9181#discussion_r2209370563) we understand that better and easier way: add `BaseID` field for `DataSource`.
- At the moment this field will be filled for `Root.io` advisories only:
```
"DataSource": {
"BaseID": "debian",
"ID": "root.io",
"Name": "Root.io Security Advisories (debian)",
"URL": "https://api.root.io/external/patch_feed"
}
```
BaseOS suffix for Name ( e.g. (Debian) ) to make it clearer what BaseID means.
- The rest `DataSource` will remain unchanged.
> feat(db): add DataSource.BaseID field

- pkg/db/db.go
- pkg/vulnsrc/alma/alma.go
- pkg/vulnsrc/alpine/alpine.go
- pkg/vulnsrc/amazon/amazon.go
- pkg/vulnsrc/amazon/amazon_test.go
- pkg/vulnsrc/azure/azure.go
- pkg/vulnsrc/azure/azure_test.go
- pkg/vulnsrc/chainguard/chainguard.go
- pkg/vulnsrc/debian/debian.go
- pkg/vulnsrc/debian/debian_test.go
- pkg/vulnsrc/echo/echo.go
- pkg/vulnsrc/echo/echo_test.go
- pkg/vulnsrc/minimos/minimos.go
- pkg/vulnsrc/oracle-oval/oracle-oval.go
- pkg/vulnsrc/oracle-oval/oracle-oval_test.go
- pkg/vulnsrc/photon/photon.go
- pkg/vulnsrc/photon/photon_test.go
- pkg/vulnsrc/rocky/rocky.go
- pkg/vulnsrc/rocky/rocky_test.go
- pkg/vulnsrc/rootio/rootio.go
- pkg/vulnsrc/rootio/rootio_test.go
- pkg/vulnsrc/suse-cvrf/suse-cvrf.go
- pkg/vulnsrc/suse-cvrf/suse-cvrf_test.go
- pkg/vulnsrc/ubuntu/ubuntu.go
- pkg/vulnsrc/wolfi/wolfi.go
- pkg/vulnsrctest/vulnsrctest.go
We have 3 implementation for `Get` function:
- `Get(osVer, pkgName)` - `Getter` interface
- `Get(osVer, pkgName, arch)` - rocky linux + oracle linux
- `Get(pkgName, repositories, nvrs)` - RedHat
This PR refactors `Getter` interface to include an architecture parameter.
These changes create one common interface for all Get function (except RedHat). 
Sources with changed `Get` function - Alma, Alpine, Amazon, Azure, Chainguard, Debian, Echo, Minimos, Oracle, Photon, Rocky, SUSE, Ubuntu, and Wolfi.
These changes will also make it easier to use sources inside another source (eg root.io + debian)
> feat(db): use GetParams (release, pkgName, arch) for `Getter` interface

- .github/workflows/cron.yml
- .github/workflows/go.yml
This PR updates GitHub Actions workflow dependencies to use commit digests instead of semantic version tags for enhanced security. The changes affect two workflow files:
- .github/workflows/cron.yml: Updates 4 action references to use SHA digests
- .github/workflows/go.yml: Updates 2 action references to use SHA digests
The specific actions updated include:
- actions/checkout@v4 → actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
- actions/setup-go@v5 → actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
- docker/login-action@v3 → docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
Each digest reference includes a comment indicating the corresponding semantic version for maintainability.
1. Security Enhancement: Using commit digests prevents potential supply chain …
> ci: use digests instead of versions for actions
