aquasecurity/trivy-db

pkg/vulnsrc/vulnsrc.go
pkg/vulnsrc/vulnsrc_test.go

test(vulnsrc): add tests for Optimizer

---

pkg/vulnsrc/vulnsrc.go
pkg/vulnsrc/vulnsrc_test.go

https://github.com/aquasecurity/trivy-db/pull/17

test(vulnsrc): add tests for NewUpdater

---

pkg/vulnsrc/photon/photon.go
pkg/vulnsrc/photon/photon_test.go
pkg/vulnsrc/photon/testdata/vuln-list/photon/3.0/apache-tomcat/CVE-2019-0199.json
pkg/vulnsrc/photon/types.go
pkg/vulnsrc/vulnerability/const.go
pkg/vulnsrc/vulnerability/vulnerability.go
pkg/vulnsrc/vulnsrc.go

 Add Photon OS

---

pkg/vulnsrc/ubuntu/ubuntu.go

13.10 was missed, 20.04 is the new LTS.

Add Ubuntu 13.10 and 20.04

---

README.md

Add a shiny badge for Trivy DB builds

---

pkg/types/types.go

types: Switch CVSS JSON tags to CamelCase

---

pkg/vulnsrc/redhat/redhat.go
pkg/vulnsrc/redhat/redhat_test.go
pkg/vulnsrc/ubuntu/ubuntu.go
pkg/vulnsrc/ubuntu/ubuntu_test.go

[Issue](https://github.com/aquasecurity/trivy-db/issues/53)

Ignore rejected vulnerabilities

---

pkg/vulnsrc/python/python.go
pkg/vulnsrc/python/python_test.go
pkg/vulnsrc/python/testdata/fixtures/python-safety-db/data/insecure_full.json

Refer 
* #73 
* https://github.com/pyupio/safety-db

Fix update python vulnerabilities no longer work

---

.github/workflows/go.yml
pkg/vulnsrc/python/python_test.go

* utilise golangci-lint-action instead of installing and running it
* closes #81

feat: use golangci-lint-action

---

pkg/db/db.go
pkg/db/db_test.go

context: https://github.com/aquasecurity/trivy/issues/684

Add new `DownloadedAt` field to Metadata

---

.gitignore
Makefile
README.md

chore: update badges in Readme

---

.github/workflows/publish.yml

Add dispatch to the publish job
[Local test with github action](https://github.com/krol3/trivy-db/actions/runs/465224524)

chore: publish with dispatch

---

pkg/dbtest/assert.go
pkg/vulnsrc/alpine/alpine.go
pkg/vulnsrc/alpine/alpine_test.go
pkg/vulnsrc/alpine/testdata/happy/vuln-list/alpine/ansible.json
pkg/vulnsrc/alpine/testdata/sad/vuln-list/alpine/ansible.json
pkg/vulnsrc/alpine/types.go

Ref https://github.com/aquasecurity/vuln-list-update/issues/49

feat(alpine): migrate to a new data source

---

Makefile

Closes https://github.com/aquasecurity/trivy-db/issues/120

fix(nodejs): move master to main

---

.github/workflows/cron.yml
Makefile
README.md

According to the feedback of Alpine maintainers, this PR changes the update interval to 6 hours.
https://twitter.com/ariadneconill/status/1402145352858451969

chore: update database every 6 hours

---

pkg/vulnsrc/debian/debian.go
pkg/vulnsrc/debian/debian_test.go
pkg/vulnsrc/debian/testdata/happy/vuln-list/debian/CVE/CVE-2016-4606.json
pkg/vulnsrc/debian/testdata/happy/vuln-list/debian/source/bullseye/main/Sources.json

Close https://github.com/aquasecurity/trivy-db/issues/152

fix(debian): handle not-affected in sid

---

.github/workflows/publish.yml

Using separate steps to publish in docker and ecr.

feat: publish ecr step

---

pkg/types/types.go

Move color severities to Trivy

refactor: remove colors

---

pkg/vulnsrc/oracle-oval/oracle-oval.go

feat: add Oracle Linux 9 support

---

pkg/vulnsrc/glad/glad.go
pkg/vulnsrc/glad/glad_test.go
pkg/vulnsrc/glad/testdata/happy/vuln-list/glad/conan/gsoap/CVE-2020-13574.json

Added support for [conan](https://conan.io/) from `glad`.

feat(glad): add conan

---

README.md

docs: add information about the db downloading

---

pkg/vulnsrc/ubuntu/ubuntu.go

add Ubuntu 22.10 (Kinetic Kudu)

feat(ubuntu): support Ubuntu 22.10

---

pkg/vulnsrc/bucket/bucket.go
pkg/vulnsrc/ghsa/ghsa.go
pkg/vulnsrc/ghsa/ghsa_test.go
pkg/vulnsrc/ghsa/testdata/happy/vuln-list/ghsa/erlang/alchemist.vim/GHSA-6x65-vqp7-5r63.json
pkg/vulnsrc/vulnerability/const.go

add ghsa erland to Trivy-DB
https://github.com/aquasecurity/trivy/issues/3346

feat(ghsa): add Erlang

---

.github/workflows/publish.yml

According to deprecation of ubuntu-18.04
https://github.com/actions/runner-images/issues/6002

hotfix: use ubuntu-latest

---

pkg/vulnsrc/alma/alma.go
pkg/vulnsrc/oracle-oval/oracle-oval.go
pkg/vulnsrc/oracle-oval/types.go

This pr adds interfaces for Parse and db updates so that who ever wants create custom db of trivy using custom implimentation, they can use.

refactor(oracle-oval) : define interfaces and added vulnerability issued date to struct

---

pkg/vulnsrc/ubuntu/types.go

feat: added public date field to capture vendor publish date for ubuntu

---

pkg/vulnsrc/alma/alma.go
pkg/vulnsrc/oracle-oval/types.go
pkg/vulnsrc/rocky/rocky.go
pkg/vulnsrc/rocky/types.go

This pr adds interfaces for Parse and db updates so that who ever wants create custom db of trivy using custom implimentation, they can use

refactor(rocky) : define interfaces and added vulnerability issued date to struct

---

pkg/vulnsrc/chainguard/chainguard.go
pkg/vulnsrc/chainguard/chainguard_test.go
pkg/vulnsrc/chainguard/testdata/happy/vuln-list/chainguard/binutils.json
pkg/vulnsrc/chainguard/testdata/sad/vuln-list/chainguard/binutils.json
pkg/vulnsrc/chainguard/types.go
pkg/vulnsrc/vulnerability/const.go
pkg/vulnsrc/vulnsrc.go

Adds support for incorporating Chainguard secdb data into Trivy DB for https://github.com/aquasecurity/trivy/issues/3630

feat(chainguard): add support for Chainguard distro

---

Makefile
pkg/vulnsrc/vulnsrc.go

This reverts commit 05620b00f6c4c9ce60b63f62761b9065a96d920c.
- This PR will be merged after https://github.com/aquasecurity/vuln-list-update/pull/235 gets merged.

Revert "chore: fall back into vuln-list-reserve (#334)"

---

pkg/vulnsrc/bucket/bucket.go
pkg/vulnsrc/ghsa/ghsa.go
pkg/vulnsrc/ghsa/ghsa_test.go
pkg/vulnsrc/ghsa/testdata/happy/vuln-list/ghsa/swift/github.com/apple/swift-nio/GHSA-7fj7-39wj-c64f.json
pkg/vulnsrc/vulnerability/const.go

feat(ghsa): add swift support

---

Makefile
pkg/vulnsrc/osv/osv.go

https://github.com/github/advisory-database/blob/ca3bc3bce8ef5430a517d4931004d2b630095d58/advisories/github-reviewed/2023/07/GHSA-3fqm-frhg-7c85/GHSA-3fqm-frhg-7c85.json#L13-L14

fix(osv): skip empty CVSS vectors

---

pkg/vulnsrc/ubuntu/ubuntu.go

Prepare for upcoming Ubuntu 24.04 Noble Numbat

Add upcoming Ubuntu 24.04

---

pkg/types/status.go
pkg/types/types.go
pkg/vulnsrc/ubuntu/testdata/vuln-list/ubuntu/CVE-2020-1234.json
pkg/vulnsrc/ubuntu/ubuntu.go
pkg/vulnsrc/ubuntu/ubuntu_test.go

Reverts aquasecurity/trivy-db#407

Revert "feat: Expose Ubuntu fix status for downstream consumption"

---

.github/workflows/cron.yml

This PR adds publishing the DB to ECR public registry as well as GHCR.

ci: add publishing into Public ECR

---

.github/workflows/cron.yml

Add Microsoft Teams Notifications for `trivy-db`
Test run - https://github.com/DmitriyLewen/trivy-db/actions/runs/11339417357/job/31534173463#step:17:1

ci(cron): add teams notification

---

pkg/vulnsrc/nvd/nvd.go

- interface metods are defined & exported to add additional logic fom Aqua Security side in "aqua-db" nvd tracker.
How has this been tested?
ran the test cases using make test and all of them passed.

refactor(vulnsrc/nvd): define interfaces

---

pkg/db/db.go

Trivy's standalone mode is not designed to run in a multi-process environment. Even if it is executed that way, [internal locking](https://github.com/etcd-io/bbolt?tab=readme-ov-file#opening-a-database) prevents any performance benefit and can cause [unexpected errors](https://github.com/aquasecurity/trivy/discussions/7758#discussioncomment-12302001).
Multi-process execution typically happens by mistake, such as:
1. Forgetting that a Trivy server instance is already running in the background.
2. Attempting to run multiple processes in parallel to speed up scanning (which does not actually improve performance).
When Trivy is run in multiple processes by mistake, it freezes without returning a proper error. This makes it difficult to understand what’s going wrong — even maintainers [have …

feat: add timeout to BoltDB open to prevent indefinite waiting
